### ISSUE TITLE
请删除此库 谢谢

### ISSUE THREAD

**Issue by MrPig66** [TheZihanGu/nbhbdm#2]
以下转自[https://zhuanlan.zhihu.com/p/139996262](https://zhuanlan.zhihu.com/p/139996262)评论
Eltrac回复TheZihanGu (作者)05-12
**顺带一提，你 GitHub 的「nbhbdm 你难道不会百度吗」，明显是直接照搬卜卜口大佬的[「buhuibaidu?」](http://buhuibaidu.me)，加了些其他的功能而未对原作者进行署名。尽管此项目未在 GitHub 被卜卜口开源，更没有明确开源协议，但是你这种直接扒站后就谎称是自己的行为是否比 PCL2 的行为更加恶劣呢？**

卜卜口回复TheZihanGu (作者)05-13
**我没有授权过这个项目的开源，也没授权复制一个相同界面功能的网站出来。我不需要你添加我的信息，请把项目和网站删除。**

TheZihanGu (作者) 回复卜卜口05-13
**根据您的要求，已将GitHub项目删除。**网站已更换源码并标注其项目仓库，但不会删除网站。
**请问，您删了吗？？？**

**Comment by TheZihanGu** [comment]
目前本项目部分代码基于[wolfbolin/baidux](https://github.com/wolfbolin/baidux)，并且按照原项目的规定在 README.md 注明了原项目链接。
本存储库存放的代码并非 卜卜口 开发的版本。你可以根据源码自行比对。
至于**相同界面功能的网站**，我不认为 卜卜口 开发[不会百度么？](https://cnm.buhuibaidu.me)后就有对其他同类项目支配的权利。
